server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mygit?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 12345678

mybatis-plus:
  mapper-location: classpath*:/mapper/**Mapper.xml

token:
  expire:
    seconds: 7200
  jwtSecret: (I:)_$^11244^%$_(S:)_@@++--(P:)_++++_.sds_(Y:)
  header: Authorization

shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379
